#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ktlint-gradle
Version  : 7.1.0
Release  : 1
URL      : https://github.com/JLLeitschuh/ktlint-gradle/archive/v7.1.0.tar.gz
Source0  : https://github.com/JLLeitschuh/ktlint-gradle/archive/v7.1.0.tar.gz
Source1  : https://plugins.gradle.org/m2/org/jlleitschuh/gradle/ktlint-gradle/7.1.0/ktlint-gradle-7.1.0.jar
Source2  : https://plugins.gradle.org/m2/org/jlleitschuh/gradle/ktlint-gradle/7.1.0/ktlint-gradle-7.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-ktlint-gradle-data = %{version}-%{release}
Requires: mvn-ktlint-gradle-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : buildreq-qmake
BuildRequires : gradle

%description
# Ktlint Gradle
**Provides a convenient wrapper plugin over the [ktlint](https://github.com/shyiko/ktlint) project.**

%package data
Summary: data components for the mvn-ktlint-gradle package.
Group: Data

%description data
data components for the mvn-ktlint-gradle package.


%package license
Summary: license components for the mvn-ktlint-gradle package.
Group: Default

%description license
license components for the mvn-ktlint-gradle package.


%prep
%setup -q -n ktlint-gradle-7.1.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-ktlint-gradle
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-ktlint-gradle/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jlleitschuh/gradle/ktlint-gradle/7.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jlleitschuh/gradle/ktlint-gradle/7.1.0/ktlint-gradle-7.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jlleitschuh/gradle/ktlint-gradle/7.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jlleitschuh/gradle/ktlint-gradle/7.1.0/ktlint-gradle-7.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jlleitschuh/gradle/ktlint-gradle/7.1.0/ktlint-gradle-7.1.0.jar
/usr/share/java/.m2/repository/org/jlleitschuh/gradle/ktlint-gradle/7.1.0/ktlint-gradle-7.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-ktlint-gradle/LICENSE.txt
